import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, Container, Heading } from "@chakra-ui/react";

// import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Box as="main" pb={8}>
      <Head>
        <title>purupurupu portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.md" pt={14}>
        <Box borderRadius="lg" bg="red" p={3} mb={6} align="center">
          purupurupuのportfolioへようこそ！
        </Box>

        <Box display={{ md: "flex" }}>
          <Box flexGrow={1}>
            <Heading as="h2" variant="page-title">
              purupurupu
            </Heading>
            <p>I'm Software Engineer</p>
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

export default Home;
